### ISSUE TITLE
Define include path/files requirements

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#16]
- Python 3.4 x86
- cx_Freeze 4.3.3 32-bit
- Qt 5.4.1 32-bit

```
C:\Python34\counterparty-gui-develop\counterparty-gui-develop>c:\python34\python.exe freeze.py bdist_msi
running bdist_msi
running build
running build_exe
Traceback (most recent call last):
  File "freeze.py", line 95, in <module>
    setup(**setup_options)
  File "c:\python34\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "c:\python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\site-packages\cx_Freeze\windist.py", line 363, in run
    self.run_command('build')
  File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\site-packages\cx_Freeze\dist.py", line 231, in run
    metadata = metadata)
  File "c:\python34\lib\site-packages\cx_Freeze\freezer.py", line 104, in __init__
    self.includeFiles = self._ProcessPathSpecs(includeFiles)
  File "c:\python34\lib\site-packages\cx_Freeze\freezer.py", line 396, in _ProcessPathSpecs
    source = os.path.normpath(source)
  File "c:\python34\lib\ntpath.py", line 491, in normpath
    if path.startswith(special_prefixes):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I tried tinkering with `freeze.py`, but I couldn't make it work. 
Would it be possible to list directories and files that need to be created or downloaded so that `freeze.py bdist_msi` can work?

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterparty-gui/commit/46d48f45edbd1f10c0781c8c9045f75874c44495
