### ISSUE TITLE
ImportError: cannot import name 'clientapi`

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-gui#42]
Trying to use counterparty-gui (develop) with develop editions of `lib` and `cli`, but it seems the GUI doesn't cooperate. `counterparty-server` and `counterparty-client` are working fine.

```
rippler@ubuntu:~$ pip3 list | grep counter
counterparty-cli (1.0.1)
counterparty-gui (1.0.0) < = also tried to build from zip archive of `develop`
counterparty-lib (9.50.0)

./counterparty-gui/counterparty-gui.py 
Traceback (most recent call last):
  File "./counterparty-gui/counterparty-gui.py", line 2, in <module>
    from counterpartygui.gui import main
  File "/home/rippler/counterparty-gui/counterpartygui/gui.py", line 29, in <module>
    from counterpartygui.api import CounterpartydAPI, CounterpartydRPCError
  File "/home/rippler/counterparty-gui/counterpartygui/api.py", line 14, in <module>
    from counterpartycli import clientapi
ImportError: cannot import name 'clientapi
```

**Comment by ouziel-slama** [comment]
should be fixed now: `clientapi` is available in `master` and `develop`
